savename = 'metrics.mat';

save(savename,...
     'SPCidics',...
     'TPRidics',... 
     'PPVidics',...
     'SPCdics',...
     'TPRdics',...
     'PPVdics',...
     'SPCgcs_dics',...
     'TPRgcs_dics',...
     'PPVgcs_dics',...
     'SPCpsiicos',...
     'TPRpsiicos',...
     'PPVpsiicos', '-v7.3');
